name: "units-test"
on:
  pull_request:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: npm ci
    - run: npm run all

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ./
      with:
        milliseconds: 1000
